export const emberekLISTA =[
    {nev: "Éva",
    kor:12,
    nem:true},
    {nev: "Ádám",
    kor:22,
    nem:false},
    {nev: "Jenő",
    kor:32,
    nem:false},
    {nev: "Bela",
    kor:42,
    nem:false},
    {nev: "Peti",
    kor:13,
    nem:false},
    {nev: "Anna",
    kor:62,
    nem:true},
    {nev: "Lilla",
    kor:18,
    nem:true},
]